name: Cloudflare_Stable_Build
on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout_repository
            uses: actions/checkout@v4

        - name: upload
            uses: cloudflare/wrangler-action@v4
            with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                command: pages deploy ${{ github.workspace }} --project-name=vingturbo --branch=main
