name: test_download_tool
on: 
  workflow_dispatch:
    inputs:
      download_url:
        description: '输入要下载的URL，多个URL用空格分隔'
        required: true
        type: string
jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download_file
        run: |
          echo "Warning: File is deleted after 1 day"
          echo "${{ github.event.inputs.download_url }}" | xargs -n1 > ./urls.txt
          echo "将要下载$(cat ./urls.txt | wc -l)个文件"
          mkdir -p downloaded_file
          aria2c --allow-overwrite=false -x 8 -s 8 -j 8 -d downloaded_file/ -i ./urls.txt
          tar --zstd -cvf downloaded_file.tar.zst downloaded_file/
      - name: Upload_to_artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded_file
          path: downloaded_file.tar.zst
          retention-days: 1